from .particlerule import *
from .possessivepronounrule import *
from .validsuffixprefix import *
from .suffix2rule_v2 import *
from .prefix10rule import *
from .prefix39rule import *
from .prefix6rule import *
from .prefix20rule import *
from .prefix1rule import *
from .reduplicationrule import *
from .infixrule import *
from .simulfixrule import *
